// Code generated by scripts/gen-openapi-versions.sh; DO NOT EDIT.

package version

// OpenAPIServices 是顯示時的固定順序。
var OpenAPIServices = []string{"VCS", "Ceph", "Common"}

// OpenAPIVersions 是本 build 所依據的各服務 OpenAPI info.version。
var OpenAPIVersions = map[string]string{
	"VCS":    "1.5.4",
	"Ceph":   "1.1.0",
	"Common": "1.2.1",
}
