#!/bin/sh
# 從 api/openapi/*.yaml 的 info.version 產生 internal/version/openapi.go。
# 由 `make gen` 呼叫，輸出到 stdout。
set -eu

extract_version() {
  # 取 info: 區塊之後第一個 version: 的值
  awk '/^info:/{flag=1} flag && /^  version:/{print $2; exit}' "$1"
}

cat <<EOF
// Code generated by scripts/gen-openapi-versions.sh; DO NOT EDIT.

package version

// OpenAPIServices 是顯示時的固定順序。
var OpenAPIServices = []string{"VCS", "Ceph", "Common"}

// OpenAPIVersions 是本 build 所依據的各服務 OpenAPI info.version。
var OpenAPIVersions = map[string]string{
	"VCS":    "$(extract_version api/openapi/VCS.yaml)",
	"Ceph":   "$(extract_version api/openapi/Ceph.yaml)",
	"Common": "$(extract_version api/openapi/Common.yaml)",
}
EOF
